/-
# Worked example: what an object type has to supply

`IndividualQuantity o k R` is indexed by its object, and the object ranges over an arbitrary
type. This module is the census of what that buys and what it costs, one section per *shape*
of object type, every claim compiled — refusals as `#check_failure`, agreements as `example`.

The census is generated by two questions, and the finding is that they have different
answers:

  * **discrimination** — can the layer tell two objects apart? *Always*, for every type, with
    nothing supplied: the gate is definitional equality of the index.
  * **designation** — can it *name* one? Only through `Designated`, which not every object
    type has, and the injectivity field is what stops an author supplying a fake.

So the useful distinction is not "objects PKC made" versus "objects a host library made". It
is **how an object carries its identity** — as a *name* (§3.3's nominal reading, where naming
and telling apart are one act) or as a *position in a structure* (a particle of a mechanical
system, a cell of a grid, where there is no name anywhere) — crossed with whether the object
type is **primitive** or **derived** from another by a construction the calculus ships
(`Composite`, a pair, an index family).

Part of the separate `Examples` library; imports only the Mathlib-free core.
-/

module

public import PropertyKindCalculus
-- Private scope only: core seals `Nat.repr` and `String.toByteArray`, so a kernel `decide`
-- over a `String` built by `toString` gets stuck without these.
import all Init.Prelude
import all Init.Data.Repr
import all Init.Data.ToString.Basic
import all Init.Data.String.Basic
import all PropertyKindCalculus.Bounds
import all PropertyKindCalculus.Unit
import all PropertyKindCalculus.IndividualQuantity
import all PropertyKindCalculus.Extensivity

@[expose] public section Blanket

namespace PropertyKindCalculus.Examples.MiniObjectTypes

open PropertyKindCalculus

/-- Mass — extensive, licensed to assemble below. -/
def massK : KindOfProperty := { id := "mass", scale := .ratio }
/-- Length — a second kind, so the kind gate can be exercised alongside the object gate. -/
def lengthK : KindOfProperty := { id := "length", scale := .ratio }

/-- The sort of whole this file assembles — §20's "sort of system", minted once. The license
below is keyed by it: aggregation is a fact about *what sort of whole* is being composed, not
about the kind alone (volume aggregates over a rigid assembly and contracts over a mixture —
the probes in `Tests/Core/Composite.lean` pin both). -/
def gridS : SortOfSystem := ⟨"four-cell grid"⟩

/-- Mass is licensed to assemble into a grid. -/
instance : Assembles gridS massK := ⟨DifferenceKind.ofScale⟩

/-! ## 1. Nominal — identity *is* the name (`System`, §3.3)

The reading PKC shipped with, and the right one for a sample, an instrument, a rover: the
object is a terminological identity and nothing else, so naming it and telling two apart are
the same act. Both questions answered, for free. -/

/-- Two soil samples, named. -/
def soilA : Object := ⟨"soil sample A"⟩
/-- The second sample. -/
def soilB : Object := ⟨"soil sample B"⟩

/-- Discrimination: two masses of the *same* sample add. -/
example (x y : IndividualQuantity soilA massK Int) : IndividualQuantity soilA massK Int :=
  IndividualQuantity.add DifferenceKind.ofScale x y

/- Discrimination, the refusal: masses of *different* samples do not. -/
#check_failure fun (x : IndividualQuantity soilA massK Int)
    (y : IndividualQuantity soilB massK Int) => IndividualQuantity.add DifferenceKind.ofScale x y

/-- Designation: a nominal object designates itself, so the individual property names it. -/
example (x : IndividualQuantity soilA massK Int) :
    x.toIndividualProperty.carrier = soilA := rfl

/-! ## 2. Structural — identity is a *position*, and there is no name

The shape a host library hands over: a particle of a mechanical system, a cell of a mesh.
Stated here at its full generality — an arbitrary type `P`, about which nothing whatever is
assumed — because that is exactly how much the gate needs.

The two questions come apart here, and this is the finding the parameterization exposes: the
gate costs nothing and the designation is *absent*, not merely inconvenient. -/

section Structural
variable {P : Type} {p q : P}

/-- Discrimination on a bare type variable: same object, same kind, sums. Nothing is assumed
about `P` — no `DecidableEq`, no naming scheme, no instance at all. -/
example (x y : IndividualQuantity p massK Int) : IndividualQuantity p massK Int :=
  IndividualQuantity.add DifferenceKind.ofScale x y

/- Two *different* objects of that same bare type: refused, definitionally. -/
#check_failure fun {P : Type} {p q : P} (x : IndividualQuantity p massK Int)
    (y : IndividualQuantity q massK Int) => IndividualQuantity.add DifferenceKind.ofScale x y

/- And the kind gate rides alongside it: one object, two kinds, still refused. -/
#check_failure fun {P : Type} {p : P} (x : IndividualQuantity p massK Int)
    (y : IndividualQuantity p lengthK Int) => IndividualQuantity.add DifferenceKind.ofScale x y

/- **Designation is absent.** No instance, and none can be inferred — the honest report for a
type whose objects carry no identity of their own. -/
#check_failure (inferInstance : Designated P)

/- So the one declaration that names an object does not typecheck here. That is not a gap in
the parameterization; it is the parameterization saying what is true. -/
#check_failure fun {P : Type} {p : P} (x : IndividualQuantity p massK Int) =>
  x.toIndividualProperty

end Structural

/-! ## 3. Indexed — the name is *computed* from the position

Between the two: a pixel `(i, j)`, a spectral band, a layer. Identity is a position, as in §2,
but the position determines a name, so `Designated` is derivable rather than absent — and the
injectivity that makes it a designation is a real obligation, discharged here by `decide`
because the index set is finite and concrete. -/

/-- A four-cell grid, indexed. -/
abbrev Cell := Fin 4

/-- The cells designate themselves through their index. The injectivity field is the claim:
distinct cells get distinct names, checked rather than assumed. -/
instance : Designated Cell where
  designation i := ⟨"cell " ++ toString i.val⟩
  designation_inj {x y} h := by revert x y h; decide

/-- And the cells *instantiate a sort* — the arrow from the particular to its universal
(`Sorted`), declared once per model. Nothing in this file consumes it yet; it is the seam the
§20 dedicated kind attaches to, where a kind-of-property is dedicated to a *sort* of system
rather than to a particular. -/
instance : Sorted Cell := ⟨fun _ => ⟨"grid cell"⟩⟩

/-- Designation works, and reads as the position it came from. -/
example (x : IndividualQuantity (0 : Cell) massK Int) :
    x.toIndividualProperty.carrier = ⟨"cell 0"⟩ := rfl

/- The gate is unchanged: two cells' masses do not add. -/
#check_failure fun (x : IndividualQuantity (0 : Cell) massK Int)
    (y : IndividualQuantity (1 : Cell) massK Int) => IndividualQuantity.add DifferenceKind.ofScale x y

/-! ## 4. Composite — a *derived* object type, whole and parts in one

The construction `Composite.lean` ships, and the one an aggregation needs: the total mass
characterizes an object that a bare part type does not contain, so the whole and the parts
must inhabit one type or the arithmetic cannot relate them. Derived from any of the shapes
above — here from the indexed cells. -/

/-- The four cells, as the parts of one grid. -/
def grid : Decomposition Cell := Decomposition.ofParts 0 [1, 2, 3]

/-- One kilogram per cell, each quantity characterizing *its own* cell. -/
def cellMass (c : Cell) : IndividualQuantity (Composite.part (σ := gridS) c) massK Int := ⟨1⟩

/-- The total mass of the grid: assembled over the mereology, characterizing the whole. -/
def gridMass : IndividualQuantity (Composite.whole : Composite gridS Cell) massK Int :=
  assemble gridS Composite.whole Composite.part grid cellMass

/-- Four cells of one kilogram assemble to four. -/
example : gridMass.magnitude = 4 := rfl

/- **MR22.** A whole-composite quantity and a part quantity do not add: they characterize
different objects, and the object types now *say* so. -/
#check_failure IndividualQuantity.add (k := massK) DifferenceKind.ofScale gridMass (cellMass 0)

/- **The license is opt-in.** `lengthK` has no `Assembles` instance, so the sum of the cells'
lengths — which is not the grid's length — is not a term anyone can write. -/
#check_failure fun (f : (c : Cell) →
      IndividualQuantity (Composite.part (σ := gridS) c) lengthK Int) =>
  assemble (k := lengthK) gridS Composite.whole Composite.part grid f

/-- Designating a composite is a *commitment*: the author names the whole and shows no part
already answers to that name. `Composite.designated` takes the proof; there is no instance
that would guess. -/
example : Designated (Composite gridS Cell) :=
  Composite.designated ⟨"the grid"⟩ (by decide)

/-! ## 5. Joint — one quantity, two objects (MR23)

A flow, a transfer, a torque delivered across a coupling characterizes an *ordered pair* of
systems. Under the parameterization that is an object type like any other, `O₁ × O₂`, and the
gate falls out with nothing added.

Designation is where this shape is instructive, and the lesson is a negative one. -/

/-- The interface object: what a delivered quantity characterizes. -/
abbrev Interface := Object × Object

/-- A quantity of the coupling from `soilA` to `soilB`. -/
def flowAB : IndividualQuantity ((soilA, soilB) : Interface) massK Int := ⟨7⟩

/- The pair is ordered, so the reversed coupling is a different object: refused. -/
#check_failure fun (y : IndividualQuantity ((soilB, soilA) : Interface) massK Int) =>
  IndividualQuantity.add DifferenceKind.ofScale flowAB y

/-- **Why designation is not free for a derived object type.** The obvious nominal encoding of
a pair is to concatenate the two names with a separator — and it is *not injective*, because
the separator can occur inside a name. Two different couplings, one name. This is the reason
`Designated` carries an injectivity obligation rather than just a function: the encoding an
author reaches for first is the one that fails. -/
example :
    ((⟨"a / b"⟩, ⟨"c"⟩) : Interface) ≠ ((⟨"a"⟩, ⟨"b / c"⟩) : Interface)
      ∧ (fun x : Interface => System.mk (x.1.id ++ " / " ++ x.2.id)) (⟨"a / b"⟩, ⟨"c"⟩)
          = (fun x : Interface => System.mk (x.1.id ++ " / " ++ x.2.id)) (⟨"a"⟩, ⟨"b / c"⟩) :=
  ⟨by decide, rfl⟩

/-! ## 6. Singleton — one object, and the index costs nothing

The other end of the range, and the one that matters for the ergonomic objection: a model with
exactly one system pays no ceremony for the object layer, because there is only one term to
write and it is `()`. Worth stating because it is what makes the parameterization safe to
adopt everywhere — the layer is not a tax on models that have nothing to disambiguate. -/

/-- The single system a one-object model is about. -/
instance : Designated Unit where
  designation _ := ⟨"the apparatus"⟩
  designation_inj := by rintro ⟨⟩ ⟨⟩ _; rfl

/-- With one object, every same-kind sum is available — the gate refuses nothing, because
there is nothing to refuse. -/
example (x y : IndividualQuantity () massK Int) : IndividualQuantity () massK Int :=
  IndividualQuantity.add DifferenceKind.ofScale x y

/-- And the designation still reads, so the terminological half is not given up. -/
example (x : IndividualQuantity () massK Int) :
    x.toIndividualProperty.carrier = ⟨"the apparatus"⟩ := rfl

/-! ## 7. Combinations — and the two halves compose differently

The shapes above are not a closed list to choose from. They compose, because they are types
and types compose, and a realistic model combines them: a quantity of *this instrument*
(nominal), at *this pixel* (indexed), of *that particle* (structural) is a quantity of the
triple.

What is worth knowing is that the **gate** and the **designation** compose under different
conditions, and the difference is exactly the one the census is organized around. -/

section Combination
variable {P : Type}

/-- A three-way combination: a named instrument, an indexed cell, and a structural object
supplied by a host library about which nothing is assumed. -/
abbrev Site (P : Type) := Object × Cell × P

/-- **The gate composes for free and unconditionally.** Two quantities of one site add, with
no instance of any kind in scope for `P`. -/
example (o : Object) (c : Cell) (p : P)
    (x y : IndividualQuantity ((o, c, p) : Site P) massK Int) :
    IndividualQuantity ((o, c, p) : Site P) massK Int :=
  IndividualQuantity.add DifferenceKind.ofScale x y

/- Differ in *any one* factor and the sum is refused — here in the indexed factor alone, with
the instrument and the particle held fixed. -/
#check_failure fun {P : Type} (o : Object) (p : P)
    (x : IndividualQuantity ((o, (0 : Cell), p) : Site P) massK Int)
    (y : IndividualQuantity ((o, (1 : Cell), p) : Site P) massK Int) =>
  IndividualQuantity.add DifferenceKind.ofScale x y

/- **The designation does not compose unconditionally**: one anonymous factor makes the whole
triple anonymous. That is the right answer, not a limitation — a name for the triple would
have to name the particle, and there is no name to give. -/
#check_failure (inferInstance : Designated (Site P))

end Combination

/-- The naming is injective — 256 pairs of sites, checked. Over an infinite object type this
is a lemma the author owes; over a finite one it is `decide`. -/
theorem cellPairName_inj :
    ∀ a b c d : Cell,
      ("cell " ++ toString a.val ++ "/" ++ toString b.val)
        = ("cell " ++ toString c.val ++ "/" ++ toString d.val) → a = c ∧ b = d := by decide

/-- **When every factor is designated, one line does it.** `Designated.ofInjective` is the
composition principle: name the combination however the model names it, and show the naming is
injective. That is the whole of what composing a designation requires. -/
instance : Designated (Cell × Cell) :=
  Designated.ofInjective
    (fun x : Cell × Cell => (⟨"cell " ++ toString x.1.val ++ "/" ++ toString x.2.val⟩ : Object))
    (fun {x y} h => by
      have hb := cellPairName_inj x.1 x.2 y.1 y.2 (by injection h)
      cases x; cases y
      simp only [Prod.mk.injEq]
      exact hb)

/-- The composed designation reads as the pair it came from. -/
example (x : IndividualQuantity (((0 : Cell), (1 : Cell)) : Cell × Cell) massK Int) :
    x.toIndividualProperty.carrier = ⟨"cell 0/1"⟩ := rfl

/-! **So the shape of the answer is:** the object index needs no taxonomy, because a type is
already whatever discrimination the model has; and the designation needs one combinator per
way of building an object type, each carrying its own obligation. The library ships the
combinators (`Composite`, `Designated.ofInjective`, `Designated.prod`) and refuses to ship the
naming conventions, which is why every one of them takes a proof. -/

end PropertyKindCalculus.Examples.MiniObjectTypes

end Blanket
