/-
# Validation probes — the flow-digraph theorems, the kind graph, and the SCC gate

Three dangers closed for the `Graph` library:

  * **vacuity** — the flow-digraph theorems are applied at the core influence probes'
    concrete graph: the sound direction of sensitivity scoping produces an actual
    non-reachability fact, the acyclicity bridge an actual partial order;
  * **dead executability** — the kind-level component computation is driven at a
    hand-built graph with a known cluster, and at a crafted laundering loop harvested
    from this very file (two `ReciprocalKind` hypotheses closing a cycle between two
    role-distinct kinds), where the `#kind_scc` report finds the cluster and the
    `#kind_scc_clean` gate throws unless the cluster is declared as an allow group;
  * **silent axioms** — the bridge theorems' profiles are pinned.
-/

import PropertyKindCalculus.Graph
import PropertyKindCalculus.Tests.Core.Influence

namespace PropertyKindCalculus.Tests.Graph

open PropertyKindCalculus Provenance
open PropertyKindCalculus.Tests.Influence (G)

/-! ### The flow-digraph theorems, applied -/

-- Sensitivity scoping's sound direction: the probe's `false` is a non-reachability
-- theorem about the value flow.
example : ¬(G.flowDigraph).Reachable "cfg" "out" :=
  not_reachable_of_mayInfluence_eq_false (by decide)

-- And its converse reading: the probe's `true` is a reachability witness.
example : (G.flowDigraph).Reachable "in1" "out" :=
  mayInfluence_iff.mp (by decide)

-- The acyclicity bridge, applied: influence on the probe graph is a partial order.
example : IsPartialOrder String (G.flowDigraph).Reachable :=
  Provenance.Acyclic.isPartialOrder (by decide)

-- Budgets are finite sums, applied: on the (executably) acyclic probe graph, the
-- incidence-quiver paths between any two vertices form a finite type.
example (v w : Provenance.IncidenceVert G) : Finite (Quiver.Path v w) :=
  Provenance.Acyclic.finite_incidencePath (by decide) v w

/-! ### The kind-level component computation, hand-built -/

/-- Three kinds, a two-kind cycle (one arc authored twice), and a tail: cluster
`{0, 1}`, hierarchy edge to `2`. -/
def kg : KindGraph :=
  { kinds := #[`kA, `kB, `kC]
    edges := #[⟨0, 1, `auth, `viaK⟩, ⟨1, 0, `auth, `viaK⟩, ⟨1, 2, `auth, `viaK⟩,
               ⟨0, 1, `auth2, `viaK⟩] }

#guard kg.interderivable 0 1
#guard !(kg.interderivable 1 2)
#guard kg.clusters.map (·.size) == #[2, 1]
#guard kg.acyclicB == false
#guard (kg.hierarchyEdges.map fun e => (e.src, e.dst)) == #[(1, 2)]

-- The D2 renderers on the same graph: the cluster diagram carries the doubly authored
-- arc as a `×2` multiplicity; the condensation draws the cluster as one hexagon named
-- by its representative, with the tail as the sole hierarchy arrow.
/--
info: # generated by #kind_scc_d2 — regenerate with the producing script, do not edit
direction: right
kA
kB
kA -> kB: "viaK ×2"
kB -> kA: "viaK"
-/
#guard_msgs in #eval IO.print (kg.d2Cluster #[0, 1])

/--
info: # generated by #kind_scc_d2 — regenerate with the producing script, do not edit
direction: down
kC
scc_kA: {
  label: "kA ⋯ (2 kinds)"
  shape: hexagon
}
scc_kA -> kC
-/
#guard_msgs in #eval IO.print kg.d2Condensation

/-- Two kinds sharing a short name across namespaces: the renderers must qualify the
colliders (dots swapped for underscores in the identifier, kept in the label), not
merge their nodes. -/
def kgDup : KindGraph :=
  { kinds := #[`Alg.kD, `Gen.kD]
    edges := #[⟨0, 1, `auth, `viaK⟩, ⟨1, 0, `auth, `viaK⟩] }

/--
info: # generated by #kind_scc_d2 — regenerate with the producing script, do not edit
direction: right
Alg_kD: "Alg.kD"
Gen_kD: "Gen.kD"
Alg_kD -> Gen_kD: "viaK"
Gen_kD -> Alg_kD: "viaK"
-/
#guard_msgs in #eval IO.print (kgDup.d2Cluster #[0, 1])

/-! ### The SCC report and gate on a crafted laundering loop

Two role-distinct kinds wired into a cycle by two `ReciprocalKind` hypotheses — every
step licensed, no attest anywhere — plus a third kind derivable from the cluster. The
scan reads hypothesis binders, so no witness needs to be provable for the loop to be
visible, which is the point: the *rules* close the cycle before any value walks it. -/

/-- A probe kind. -/
def kX : KindOfProperty := { id := "kX", scale := .ratio }
/-- A probe kind, role-distinct from `kX`. -/
def kY : KindOfProperty := { id := "kY", scale := .ratio }
/-- A probe kind downstream of the cluster. -/
def kZ : KindOfProperty := { id := "kZ", scale := .ratio }

theorem xToY (_h : ReciprocalKind kX kY) : True := trivial
theorem yToX (_h : ReciprocalKind kY kX) : True := trivial
theorem yToZ (_h : ReciprocalKind kY kZ) : True := trivial

/--
info: kind graph — 3 kind(s), 3 licensed derivation edge(s), 1 inter-derivable cluster(s) of size ≥ 2, 0 within-kind edge(s)
  ⚠ {kX, kY}
      kX → kY [ReciprocalKind] (PropertyKindCalculus.Tests.Graph.xToY)
      kY → kX [ReciprocalKind] (PropertyKindCalculus.Tests.Graph.yToX)
-/
#guard_msgs in #kind_scc PropertyKindCalculus.Tests.Graph

/--
error: kind-level SCC: 1 undeclared inter-derivable cluster(s)
  ⚠ {kX, kY}
      kX → kY [ReciprocalKind] (PropertyKindCalculus.Tests.Graph.xToY)
      kY → kX [ReciprocalKind] (PropertyKindCalculus.Tests.Graph.yToX)

Each cluster's kinds can be manufactured from one another by licensed derivations alone — no attest, no review. If the cluster is intentional (representation variants of one role), declare it: `#kind_scc_clean … (kindA kindB)`. If it is not, one of the printed witness registrations merges two roles and must be split or retired.
-/
#guard_msgs in #kind_scc_clean PropertyKindCalculus.Tests.Graph

-- Declared, the same cluster passes the gate.
#kind_scc_clean PropertyKindCalculus.Tests.Graph (kX kY)

/-! ### The SCC footprint of a declared boundary

The footprint reads a `Provenance.Contract` against the same kind graph: which
components the boundary's kinds fall into, which ports share a kind (swappable however
separated the components), and where the guarantee is review-strength. The probe
boundary touches the `{kX, kY}` cluster *and* the downstream `kZ`, carries a same-kind
pair (`x`/`lo`, the swap no kind graph sees), and re-enters through one attest — so
every section of the report is exercised non-vacuously. -/

/-- A cluster-interior step: two same-kind operands — the swap the kind algebra cannot
refuse — and a cluster partner, attested onto the downstream kind. -/
def clusterStep (x lo : Quantity kX Nat) (y : Quantity kY Nat) : Quantity kZ Nat :=
  Quantity.attest "probe re-entry" (x.magnitude + lo.magnitude + y.magnitude)

/-- The probe step's declared boundary. -/
def clusterBoundary :
    Provenance.Contract Provenance.NodeId Provenance.KindRef where
  name := "footprint probe"
  members := [``clusterStep]
  ports := [
    ⟨(Provenance.NodeId.binder "x").within ``clusterStep, .decl ``kX, .input⟩,
    ⟨(Provenance.NodeId.binder "lo").within ``clusterStep, .decl ``kX, .input⟩,
    ⟨(Provenance.NodeId.binder "y").within ``clusterStep, .decl ``kY, .input⟩,
    ⟨Provenance.NodeId.result.within ``clusterStep, .decl ``kZ, .output⟩]
  exits := []

/--
info: kind footprint of 'footprint probe': 3 kind(s) in the graph; 1 derivation cluster(s) of size ≥ 2 touched, 1 singleton kind(s)
  cluster kX (2 kinds): kX, kY
same-kind ports — 1 group(s):
  kX: clusterStep/x (input), clusterStep/lo (input)
review-strength sites — 0 crossing(s), 1 attested intro(s), 0 declared exit(s):
  attested "probe re-entry" clusterStep/_1 : kZ
verdict: type-strength: the kinds span 2 components; 1 same-kind group(s) swap invisibly to any cluster separation; review-strength at 1 site(s)
-/
#guard_msgs (whitespace := lax) in
#kind_footprint clusterBoundary PropertyKindCalculus.Tests.Graph

/-! ### Axiom profiles -/

/-- info: 'PropertyKindCalculus.Provenance.mem_influencedFrom_iff' depends on axioms: [propext,
Classical.choice, Quot.sound] -/
#guard_msgs in #print axioms Provenance.mem_influencedFrom_iff

/-- info: 'PropertyKindCalculus.Provenance.mem_ancestorsOf_iff' depends on axioms: [propext,
Classical.choice, Quot.sound] -/
#guard_msgs in #print axioms Provenance.mem_ancestorsOf_iff

/-- info: 'PropertyKindCalculus.Provenance.mayInfluence_iff' depends on axioms: [propext,
Classical.choice, Quot.sound] -/
#guard_msgs in #print axioms Provenance.mayInfluence_iff

/-- info: 'PropertyKindCalculus.Provenance.acyclic_iff_isAcyclic' depends on axioms: [propext,
Classical.choice, Quot.sound] -/
#guard_msgs in #print axioms Provenance.acyclic_iff_isAcyclic

/-- info: 'PropertyKindCalculus.Provenance.Acyclic.finite_incidencePath' depends on axioms: [propext,
 Classical.choice,
 Quot.sound] -/
#guard_msgs in #print axioms Provenance.Acyclic.finite_incidencePath

end PropertyKindCalculus.Tests.Graph
